# Form implementation generated from reading ui file '/Volumes/data/work/aiwork/python_study/qt/qt6/exam03_stylesheet/layout_main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 602)
        Form.setWindowOpacity(13.0)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("color:#00ff00;\n"
"background-color:#000;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setStyleSheet("color:rgb(255, 238, 0);\n"
"background-color : black;\n"
"padding : 8px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setStyleSheet("background-color : black;\n"
"color : white;\n"
"margin:8px")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 64))
        self.label_4.setStyleSheet("color: red;\n"
"border: 2px solid blue;\n"
"font-size: 20px;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 128))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 64, 64))
        self.label_5.setStyleSheet("border : 1px solid black;\n"
"border-radius : 8px;")
        self.label_5.setObjectName("label_5")
        self.btnHome = QtWidgets.QLabel(parent=self.frame)
        self.btnHome.setGeometry(QtCore.QRect(160, 20, 64, 64))
        self.btnHome.setStyleSheet("border: 1px solid black;\n"
"border-radius : 8px;\n"
"padding : 2px;")
        self.btnHome.setText("")
#         self.btnHome.setPixmap(QtGui.QPixmap(":/btn_icon/home.png"))
        self.btnHome.setScaledContents(True)
        self.btnHome.setObjectName("btnHome")
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 247, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "padding"))
        self.label_3.setText(_translate("Form", "margin"))
        self.label_4.setText(_translate("Form", "alignment , minimumSize"))
        self.label_5.setText(_translate("Form", "Test"))

